---
# App of Apps Pattern for Platform Infrastructure
# This is the root application that manages all other platform applications

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: argocd
  labels:
    app.kubernetes.io/name: platform-apps
    app.kubernetes.io/part-of: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project configuration
  project: platform
  
  # Source configuration
  source:
    repoURL: https://github.com/5dlabs/cto
    targetRevision: argo
    path: infra/gitops
    
    # Directory configuration
    directory:
      recurse: true
      include: "applications/*.yaml"
      exclude: "*.md"
  
  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Revision history
  revisionHistoryLimit: 10