---
# Argo CD Application for Argo Workflows
# This manages the Argo Workflows installation via GitOps

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    app.kubernetes.io/name: argo-workflows
    app.kubernetes.io/part-of: platform
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project configuration
  project: platform
  
  # Source configuration
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 0.45.21
    chart: argo-workflows
    
    # Helm configuration
    helm:
      valueFiles: []
      values: |
        # Use values from our local configuration file
        artifactRepository:
          archiveLogs: true
          filesystem:
            archivePath: /tmp/artifacts
        persistence: {}
        server:
          authModes:
            - server
          service:
            type: NodePort
            nodePort: 30081
        workflow:
          serviceAccount:
            annotations: {}
          rbac:
            create: true
  
  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
  
  # Revision history
  revisionHistoryLimit: 5