---
# Argo CD Application for Platform Controller
# This enables GitOps deployment of the controller service

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: platform
  annotations:
    # Exclude CRDs from GitOps management (managed by existing Helm release)
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project configuration
  project: platform
  
  # Source configuration
  source:
    repoURL: https://github.com/5dlabs/platform
    targetRevision: argo
    path: infra/charts/controller
    
    # Helm configuration
    helm:
      valueFiles:
        - values.yaml
      
      # Override values for GitOps deployment
      parameters:
        - name: image.repository
          value: ghcr.io/5dlabs/platform/controller
        - name: image.tag
          value: latest
        - name: image.pullPolicy
          value: Always
        
        # Skip CRDs - managed by existing Helm release
        
        # Resource configuration
        - name: resources.limits.cpu
          value: 1000m
        - name: resources.limits.memory
          value: 1Gi
        - name: resources.requests.cpu
          value: 500m
        - name: resources.requests.memory
          value: 512Mi
        
        # Monitoring
        - name: metrics.enabled
          value: "true"
        - name: metrics.serviceMonitor.enabled
          value: "false"  # Enable when Prometheus operator is available
  
  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: agent-platform
  
  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
      - SkipDryRunOnMissingResource=true
      - Replace=true
    
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences for better GitOps experience
  ignoreDifferences:
    # Completely ignore CRDs to prevent duplication warnings
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /
    # Ignore deployment replicas (managed by HPA/manual scaling)
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    # Ignore secret data changes (managed externally)
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
  
  # Revision history
  revisionHistoryLimit: 10