---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.external-secrets.io
    chart: external-secrets
    targetRevision: 0.12.1
    helm:
      values: |
        installCRDs: true
        serviceMonitor:
          enabled: false
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 128Mi
        env:
          ANTHROPIC_API_KEY:
            value: "${ANTHROPIC_API_KEY}"
          PERPLEXITY_API_KEY:
            value: "${PERPLEXITY_API_KEY}"
          OPENAI_API_KEY:
            value: "${OPENAI_API_KEY}"
          GOOGLE_API_KEY:
            value: "${GOOGLE_API_KEY}"
          XAI_API_KEY:
            value: "${XAI_API_KEY}"
          GEMINI_API_KEY:
            value: "${GEMINI_API_KEY}"
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true