---
# Argo CD Application for QuestDB Operator
# Manages QuestDB time-series database instances on Kubernetes
# Source: https://github.com/5dlabs/questdb-operator (fork with fixed image tag)

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: questdb-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: questdb-operator
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: database
    app.kubernetes.io/type: timeseries
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project configuration
  project: platform

  # Source configuration - Deploy from our fork with the fixed image tag
  source:
    repoURL: https://github.com/5dlabs/questdb-operator.git
    targetRevision: fix/v0.5.1-image-tag  # Branch with fixed v0.5.1 image tag
    path: config/default

    # Kustomize configuration
    kustomize:
      namespace: questdb-operator

      # Add common labels
      commonLabels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: platform

      # Add resource limits (no image patch needed anymore!)
      patches:
        - target:
            kind: Deployment
            name: questdb-operator-controller-manager
          patch: |
            - op: add
              path: /spec/template/spec/containers/0/resources
              value:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi

  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: questdb-operator

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Use server-side apply for CRDs
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  # Ignore certain differences in CRDs
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion
        - /spec/preserveUnknownFields
        - /metadata/annotations
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

# Note: Health checks are automatically handled by ArgoCD

  # Revision history
  revisionHistoryLimit: 5
