---
# Argo CD Application for Spotahome Redis Operator
# Manages Redis failover clusters on Kubernetes
# Source: https://github.com/spotahome/redis-operator

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-operator
  namespace: argocd
  labels:
    app.kubernetes.io/name: redis-operator
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: database
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project configuration
  project: platform

  # Source configuration - Using Spotahome's manifests
  source:
    repoURL: https://github.com/spotahome/redis-operator
    targetRevision: v1.3.0-rc1  # Latest available version (stable v1.3.0 not yet released)
    path: manifests

    # Kustomize configuration to deploy the operator
    kustomize:
      namespace: redis-operator

      # Optional: Add resource customizations
      commonLabels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: platform

  # Destination configuration
  destination:
    server: https://kubernetes.default.svc
    namespace: redis-operator

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Use server-side apply for CRDs
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  # Ignore certain differences in CRDs
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion
        - /spec/preserveUnknownFields
        - /metadata/annotations
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas  # Allow HPA to manage replicas

  # Health assessment for the operator
  health:
    # Custom health check for the redis operator deployment
    - group: apps
      kind: Deployment
      namespace: redis-operator
      name: redisoperator

  # Revision history
  revisionHistoryLimit: 5
