#!/bin/sh
set -e

echo "════════════════════════════════════════════════════════════════"
echo "║              DOCUMENTATION PR CREATION HOOK                  ║"
echo "════════════════════════════════════════════════════════════════"

# This hook runs after Claude completes documentation generation
# It handles git operations from the repository root

# Check if we're in a docs generation job
if [ "$SERVICE_NAME" != "docs-generator" ]; then
  echo "Not a documentation generation job, skipping PR creation"
  exit 0
fi

# Source GitHub environment if it exists
if [ -f /workspace/.github-env ]; then
  . /workspace/.github-env
  echo "✓ GitHub authentication configured"
else
  echo "✗ No GitHub authentication found, skipping PR creation"
  exit 0
fi

# Change to repository root
cd /workspace
echo "Working directory: $(pwd)"

# Check if we have any changes
if ! git diff --quiet || ! git diff --cached --quiet || [ -n "$(git ls-files --others --exclude-standard)" ]; then
  echo "✓ Found changes to commit"
  
  # Get branch information from environment or use defaults
  TARGET_BRANCH="${TARGET_BRANCH:-docs-generation-$(date +%Y%m%d-%H%M%S)}"
  SOURCE_BRANCH="${SOURCE_BRANCH:-main}"
  
  echo "Creating documentation branch: $TARGET_BRANCH"
  
  # Create and checkout new branch
  git checkout -b "$TARGET_BRANCH"
  
  # Add all documentation changes
  echo "Adding documentation files..."
  git add -A
  
  # Create commit
  echo "Creating commit..."
  git commit -m "docs: generate comprehensive task documentation

- Generated documentation for all Task Master tasks
- Created structured markdown files in .taskmaster/docs/
- Added task details, implementation guides, and testing strategies

🤖 Generated with Claude (orchestrator task init-docs)"
  
  # Push to remote
  echo "Pushing to remote..."
  git push -u origin "$TARGET_BRANCH"
  
  # Create pull request
  echo "Creating pull request..."
  gh pr create \
    --title "docs: Task Master documentation update" \
    --body "## Summary

This PR contains automatically generated documentation for all Task Master tasks.

### Changes
- Generated comprehensive documentation in \`.taskmaster/docs/\`
- Each task has its own directory with structured documentation
- Includes implementation details, dependencies, and testing strategies

### Generated by
- Command: \`orchestrator task init-docs --model ${MODEL:-opus}\`
- Branch: $TARGET_BRANCH
- Time: $(date)

🤖 This documentation was generated automatically using Claude." \
    --base "$SOURCE_BRANCH"
  
  echo "✓ Pull request created successfully!"
else
  echo "No changes detected, skipping PR creation"
fi

echo "════════════════════════════════════════════════════════════════"
echo "║            DOCUMENTATION PR CREATION COMPLETE                ║"
echo "════════════════════════════════════════════════════════════════"