apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: postgres-general
  namespace: databases
  labels:
    team: platform
    app.kubernetes.io/name: postgres-general
    app.kubernetes.io/component: database
spec:
  teamId: platform
  postgresql:
    version: "16"
    parameters:
      shared_preload_libraries: "bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon"
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
  numberOfInstances: 1
  volume:
    size: 50Gi
    storageClass: local-path
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 2000m
  users:
    admin:
      - SUPERUSER
      - CREATEDB
    app_user:
      - NOSUPERUSER
      - INHERIT
      - CREATEDB
      - NOCREATEROLE
      - NOREPLICATION
    readonly:
      - NOSUPERUSER
      - INHERIT
      - NOCREATEDB
      - NOCREATEROLE
      - NOREPLICATION
  databases:
    app_db: app_user
    general_db: admin
    metrics_db: admin
  preparedDatabases:
    app_db:
      defaultUsers: true
      extensions:
        pg_stat_statements: "public"
        uuid-ossp: "public"
    general_db:
      defaultUsers: true
      extensions:
        hstore: "public"
        pg_stat_statements: "public"
        pg_trgm: "public"
        pgcrypto: "public"
        uuid-ossp: "public"
    metrics_db:
      defaultUsers: true
      extensions:
        pg_stat_statements: "public"
  enableConnectionPooler: true
  connectionPooler:
    numberOfInstances: 1
    mode: "transaction"
    schema: "pooler"
    user: "pooler"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 500Mi
  maintenanceWindows:
    - "03:00-04:00"
