apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redis-general
  namespace: databases
  labels:
    team: platform
    app.kubernetes.io/name: redis-general
    app.kubernetes.io/component: cache
spec:
  sentinel:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi
    customConfig:
      - "down-after-milliseconds 5000"
      - "failover-timeout 10000"
      - "parallel-syncs 1"
  redis:
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2Gi
    image: redis:7.2-alpine
    imagePullPolicy: IfNotPresent
    customConfig:
      - "maxmemory 1536mb"
      - "maxmemory-policy allkeys-lru"
      - "save 900 1"
      - "save 300 10"
      - "save 60 10000"
      - "appendonly yes"
      - "appendfsync everysec"
      - "no-appendfsync-on-rewrite no"
      - "auto-aof-rewrite-percentage 100"
      - "auto-aof-rewrite-min-size 64mb"
      - "tcp-keepalive 60"
      - "tcp-backlog 511"
      - "timeout 300"
      - "databases 16"
      - "slowlog-log-slower-than 10000"
      - "slowlog-max-len 128"
      - "rename-command FLUSHDB \"\""
      - "rename-command FLUSHALL \"\""
      - "rename-command KEYS \"\""
    storage:
      persistentVolumeClaim:
        metadata:
          name: redis-general-data
        spec:
          accessModes:
            - ReadWriteOnce
          storageClassName: local-path
          resources:
            requests:
              storage: 20Gi
