---
apiVersion: crd.questdb.io/v1beta1
kind: QuestDB
metadata:
  name: trader-questdb
  namespace: databases
  labels:
    team: platform
    app.kubernetes.io/name: trader-questdb
    app.kubernetes.io/component: timeseries
spec:
  image: questdb/questdb:7.3.10
  imagePullPolicy: IfNotPresent
  volume:
    size: 50Gi
    storageClassName: local-path
  resources:
    requests:
      memory: 2Gi
      cpu: 500m
    limits:
      memory: 8Gi
      cpu: 2000m
  config:
    http.enabled: "true"
    pg.enabled: "true"
    line.tcp.enabled: "true"
