---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: vector-postgres
  namespace: databases
  labels:
    team: platform
    app.kubernetes.io/name: vector-postgres
    app.kubernetes.io/component: database
spec:
  teamId: platform
  postgresql:
    version: "16"
    parameters:
      # Load extensions - pgvector doesn't need preloading, available as extension
      shared_preload_libraries: "bg_mon,pg_stat_statements,pgextwlist,pg_auth_mon,timescaledb"
      max_connections: "200"
      shared_buffers: "512MB"
      effective_cache_size: "2GB"
      maintenance_work_mem: "128MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "8MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"

      # Parallel query execution
      max_worker_processes: "4"
      max_parallel_workers_per_gather: "2"
      max_parallel_workers: "4"

      # Logging for debugging
      log_statement: "mod"
      log_duration: "off"
      log_min_duration_statement: "500ms"
      log_checkpoints: "on"
      log_connections: "on"
      log_disconnections: "on"
      log_lock_waits: "on"
      log_temp_files: "0"

      # Statement timeouts
      statement_timeout: "30s"
      lock_timeout: "10s"
      idle_in_transaction_session_timeout: "60s"

  # 2 instances for HA
  numberOfInstances: 2

  # Storage configuration
  volume:
    size: 50Gi
    storageClass: local-path

  # Resource allocation
  resources:
    requests:
      memory: 1Gi
      cpu: 500m
    limits:
      memory: 4Gi
      cpu: 2000m

  # Database users and permissions
  users:
    # Main application user
    app_user:
      - NOSUPERUSER
      - INHERIT
      - CREATEDB
      - NOCREATEROLE
      - NOREPLICATION
    # Vector operations user
    vector_user:
      - NOSUPERUSER
      - INHERIT
      - CREATEDB
      - NOCREATEROLE
      - NOREPLICATION
    # Read-only user
    readonly:
      - NOSUPERUSER
      - INHERIT
      - NOCREATEDB
      - NOCREATEROLE
      - NOREPLICATION
    # Admin user
    admin:
      - SUPERUSER
      - CREATEDB

  # Databases
  databases:
    app_db: app_user
    vector_db: vector_user
    metrics_db: admin

  # Prepared databases with extensions
  preparedDatabases:
    app_db:
      defaultUsers: true
      extensions:
        pg_stat_statements: "public"
        uuid-ossp: "public"
        hstore: "public"
        pg_trgm: "public"
        pgcrypto: "public"
    vector_db:
      defaultUsers: true
      extensions:
        vector: "public"             # Enable pgvector extension
        pg_stat_statements: "public"
        uuid-ossp: "public"
        pg_trgm: "public"            # Useful for text similarity with vectors
        pgcrypto: "public"
    metrics_db:
      defaultUsers: true
      extensions:
        pg_stat_statements: "public"
        timescaledb: "public"        # For time-series metrics

  # Connection pooler
  enableConnectionPooler: true
  connectionPooler:
    numberOfInstances: 2
    mode: "transaction"
    schema: "pooler"
    user: "pooler"
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 500Mi

  # Maintenance windows
  maintenanceWindows:
    - "03:00-04:00"