# VictoriaMetrics Single Server Helm Values for Claude Code Telemetry

# Server configuration
server:
  # Enable single server mode
  enabled: true
  
  # Image configuration
  image:
    repository: victoriametrics/victoria-metrics
    tag: v1.101.0
    pullPolicy: IfNotPresent
  
  # Resource allocation - adjusted for development environment
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  
  # Data retention period
  retentionPeriod: 12  # 12 months
  
  # Storage configuration
  persistentVolume:
    enabled: true
    size: 50Gi
    storageClass: standard  # Kind default storage class
    
  # Extra arguments for VictoriaMetrics
  extraArgs:
    maxLabelsPerTimeseries: "50"
    search.maxQueryDuration: "30s"
    search.maxConcurrentRequests: "16"
    dedup.minScrapeInterval: "1s"
    promscrape.streamParse: "true"
    # Enable Prometheus naming for OpenTelemetry metrics
    opentelemetry.usePrometheusNaming: "true"
    
  # Service configuration
  service:
    type: ClusterIP
    port: 8428
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "8428"
      prometheus.io/path: "/metrics"
  
  # Enable metrics scraping
  scrape:
    enabled: true
    config:
      global:
        scrape_interval: 15s
        scrape_timeout: 10s
      
      scrape_configs:
        # Scrape VictoriaMetrics itself
        - job_name: victoria-metrics
          static_configs:
            - targets:
                - localhost:8428
        
        # Scrape OpenTelemetry Collector metrics
        - job_name: otel-collector  
          static_configs:
            - targets:
                - otel-collector-metrics.telemetry.svc.cluster.local:8890
              labels:
                namespace: telemetry
                service: otel-collector
        
        # Scrape Claude Code metrics from OTLP collector's Prometheus endpoint
        - job_name: claude-code-metrics
          static_configs:
            - targets:
                - otel-collector-metrics.telemetry.svc.cluster.local:8889
          metric_relabel_configs:
            # Only keep claude_code metrics
            - source_labels: [__name__]
              regex: 'claude_code.*'
              action: keep

  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    fsGroup: 65534
    
  # Liveness and readiness probes
  livenessProbe:
    httpGet:
      path: /health
      port: 8428
    initialDelaySeconds: 30
    periodSeconds: 30
    
  readinessProbe:
    httpGet:
      path: /health  
      port: 8428
    initialDelaySeconds: 5
    periodSeconds: 5
    
  # Pod annotations
  podAnnotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8428"

# Disable unnecessary components for single-server setup
vmselect:
  enabled: false
  
vminsert:
  enabled: false
  
vmstorage:
  enabled: false

# Ingress configuration
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: victoria-metrics.local
      paths:
        - path: /
          pathType: Prefix
  
# Service Monitor for Prometheus Operator (if available)
serviceMonitor:
  enabled: false