# VictoriaLogs Single Server Helm Values for Claude Code Telemetry

# Server configuration
server:
  # Enable single server mode
  enabled: true
  
  # Image configuration
  image:
    repository: victoriametrics/victoria-logs
    tag: v1.24.0-victorialogs
    pullPolicy: IfNotPresent
  
  # Resource allocation - adjusted for development environment
  resources:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  
  # Data retention period
  retentionPeriod: 6M  # 6 months
  
  # Storage configuration
  persistentVolume:
    enabled: true
    size: 20Gi
    storageClass: local-path  # Using local-path provisioner
    
  # Extra arguments for VictoriaLogs
  extraArgs:
    httpListenAddr: ":9428"
    retentionPeriod: "6"
    loggerLevel: "INFO"
    search.maxQueryDuration: "30s"
    
  # Service configuration
  service:
    type: ClusterIP
    servicePort: 9428
    
  # Security context
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    
  # Liveness and readiness probes
  livenessProbe:
    httpGet:
      path: /health
      port: 9428
    initialDelaySeconds: 30
    periodSeconds: 30
    
  readinessProbe:
    httpGet:
      path: /health  
      port: 9428
    initialDelaySeconds: 5
    periodSeconds: 5

# Disable fluent-bit by default
fluent-bit:
  enabled: false

# Ingress configuration
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: victoria-logs.local
      paths:
        - path: /
          pathType: Prefix
  tls: []