#!/bin/sh
# Script to push docs and create PR

cd /workspace/example

# Push the branch
echo "Pushing branch docs/task-master-docs-20250709-213954..."
git push https://swe-1-5dlabs:${GH_TOKEN}@github.com/5dlabs/agent-platform.git HEAD

# Create PR using GitHub API
echo ""
echo "Creating PR..."
curl -X POST \
  -H "Authorization: token ${GH_TOKEN}" \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/5dlabs/agent-platform/pulls \
  -d '{
    "title": "docs: auto-generate Task Master documentation",
    "body": "## 📚 Auto-Generated Task Master Documentation\n\nThis PR contains automatically generated documentation for Task Master tasks.\n\n### 📋 Documentation Generated:\n- Comprehensive task overviews (task.md)\n- Autonomous AI prompts (prompt.md)\n- Technical design specifications (design-spec.md)\n- Acceptance criteria (acceptance-criteria.md)\n\n### 🤖 Generated by\n- Model: claude-sonnet-4-20250514\n- Task: 999999 (all tasks)\n- Branch: docs/task-master-docs-20250709-213954\n\n---\n_Automatically generated by Orchestrator Documentation Service_",
    "head": "docs/task-master-docs-20250709-213954",
    "base": "feature/example-project-and-cli"
  }'