#!/bin/bash
# Test script to show new pod naming convention

echo "New Pod Naming Convention Examples:"
echo "=================================="
echo ""
echo "Pattern: {agent}-{service}-task{id}-v{attempt}"
echo ""
echo "Examples:"
echo "  claude-agent-1-todo-api-task1-v1"
echo "  claude-agent-1-todo-api-task1-v2    (retry)"
echo "  swe-1-5dlabs-auth-service-task3-v1"
echo "  qa-bot-payment-service-task10-v1"
echo ""
echo "Benefits:"
echo "  - Agent name comes first for easier filtering"
echo "  - Service name clearly visible"
echo "  - Task ID with 'task' prefix for clarity"
echo "  - Version/attempt number at the end"
echo ""
echo "Kubernetes commands:"
echo "  # List all pods for a specific agent:"
echo "  kubectl get pods -n orchestrator | grep '^claude-agent-1'"
echo ""
echo "  # List all pods for a specific service:"
echo "  kubectl get pods -n orchestrator | grep 'todo-api'"
echo ""
echo "  # List all attempts for a specific task:"
echo "  kubectl get pods -n orchestrator | grep 'task1-v'"