---
# External Secret for ARC controller GitHub authentication
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-pat
  namespace: arc-systems
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: github-pat
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        github_token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: github-pat
      property: token

---
# External Secret for ARC runners GitHub authentication
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-pat
  namespace: arc-runners
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: secret-store
    kind: ClusterSecretStore
  target:
    name: github-pat
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        github_token: "{{ .token }}"
  data:
  - secretKey: token
    remoteRef:
      key: github-pat
      property: token