---
# Argo CD Application for QuestDB Operator (Staging)
# Manages QuestDB time-series database instances on Kubernetes
# Source: https://github.com/questdb/questdb-operator

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: questdb-operator-staging
  namespace: argocd
  labels:
    app.kubernetes.io/name: questdb-operator-staging
    app.kubernetes.io/part-of: platform
    app.kubernetes.io/component: database
    app.kubernetes.io/type: timeseries
    environment: staging
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project configuration
  project: platform

  # Source configuration - Deploy from QuestDB operator manifests
  source:
    repoURL: https://github.com/questdb/questdb-operator
    targetRevision: v0.5.1  # Latest stable version
    path: config/default

    # Kustomize configuration
    kustomize:
      namespace: questdb-operator-staging

      # Add common labels
      commonLabels:
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/part-of: platform
        environment: staging

      # Resource customizations and namespace scoping
      patches:
        - target:
            kind: Deployment
            name: questdb-operator-controller-manager
          patch: |
            - op: add
              path: /spec/template/spec/containers/0/resources
              value:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 512Mi
            - op: add
              path: /spec/template/spec/containers/0/env/-
              value:
                name: WATCH_NAMESPACE
                value: "staging,questdb-operator-staging"

  # Destination configuration - staging namespace
  destination:
    server: https://kubernetes.default.svc
    namespace: questdb-operator-staging

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true  # Use server-side apply for CRDs
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true

    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m

  # Ignore certain differences in CRDs
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/conversion
        - /spec/preserveUnknownFields
        - /metadata/annotations
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/1/clientConfig/caBundle
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle

  # Health assessment
  health:
    - group: apps
      kind: Deployment
      namespace: questdb-operator-staging
      name: questdb-operator-controller-manager

  # Revision history
  revisionHistoryLimit: 5
